# Metric configuration for sleep scoring
METRICS = {
    "hrv": {
        "weight": 0.25,
        "optimal": 50,
        "label": "HRV (ms)",
        "help": "Heart Rate Variability. Higher is better. >50ms is optimal.",
        "direction": "high",
        "range": (0, 300),
    },
    "total_sleep_hours": {
        "weight": 0.20,
        "optimal": (7, 8.5),
        "label": "Total Sleep Time (hrs)",
        "help": "Total hours of sleep per night. 7–8.5 hours is optimal.",
        "direction": "range",
        "range": (0, 24),
    },
    "sleep_efficiency": {
        "weight": 0.15,
        "optimal": 85,
        "label": "Sleep Efficiency (%)",
        "help": "Percent of time in bed spent asleep. ≥85% is optimal.",
        "direction": "high",
        "range": (0, 100),
    },
    "REM_percentage": {
        "weight": 0.10,
        "optimal": (20, 25),
        "label": "REM Sleep (%)",
        "help": "Percent of sleep spent in REM. 20–25% is optimal.",
        "direction": "range",
        "range": (0, 100),
    },
    "sleep_latency": {
        "weight": 0.10,
        "optimal": 20,
        "label": "Sleep Latency (min)",
        "help": "Minutes it takes to fall asleep. <20 min is optimal.",
        "direction": "low",
        "range": (0, 180),
    },
    "timing_consistency": {
        "weight": 0.10,
        "optimal": 1,
        "label": "Timing Consistency (hr)",
        "help": "Variation in sleep timing (bed/wake) across days. <1hr is optimal.",
        "direction": "low",
        "range": (0, 12),
    },
    "chronotype_alignment": {
        "weight": 0.10,
        "optimal": True,
        "label": "Chronotype Alignment",
        "help": "Is your sleep schedule aligned with your natural preference? (Yes/No)",
        "direction": "bool",
        "range": (False, True),
    },
} 